build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.19"
  amd64: "ghcr.io/home-assistant/amd64-base:3.19"
  armv7: "ghcr.io/home-assistant/armv7-base:3.19"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: RetroAssembly"
  org.opencontainers.image.description: "The personal retro game collection cabinet in your browser"
  org.opencontainers.image.source: "https://github.com/MichalTorma/ha-repository"
  org.opencontainers.image.licenses: "MIT"
args:
  RETROASSEMBLY_VERSION: "v4"
